const $ = id => document.getElementById(id);
const money = value => (value===null||value===undefined||Number.isNaN(value)) ? 'Not disclosed' : value >= 1 ? `$${value.toFixed(value % 1 ? 1 : 0)}B` : `$${Math.round(value * 1000)}M`;
const getSaved=(k)=>JSON.parse(localStorage.getItem(k)||'[]');
const setSaved=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function applyTheme(){ if(localStorage.getItem("dealScopeTheme")==="dark") document.body.classList.add("dark"); const b=$("themeToggle"); if(b)b.onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("dealScopeTheme",document.body.classList.contains("dark")?"dark":"light")}; }
function setActiveNav(){const page=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('nav a').forEach(a=>{if(a.getAttribute('href')===page)a.classList.add('active')})}
function toggleWatch(id){id=String(id);let w=getSaved('dealScopeWatchlist').map(String);w=w.includes(id)?w.filter(x=>x!==id):[...w,id];setSaved('dealScopeWatchlist',w);location.reload()}
function toggleCompare(id){id=String(id);let c=getSaved('dealScopeCompare').map(String);if(c.includes(id))c=c.filter(x=>x!==id);else if(c.length<3)c.push(id);else return alert('You can compare up to three deals.');setSaved('dealScopeCompare',c);location.reload()}
function dealCard(d){const w=getSaved('dealScopeWatchlist').map(String).includes(String(d.id)),c=getSaved('dealScopeCompare').map(String).includes(String(d.id));return `<article class="deal-card"><div class="deal-date">${d.date}<br><span class="deal-meta">${d.status}</span>${d.automated?'<span class="live-badge">AUTO</span>':''}</div><div><h3><a href="deal.html?id=${d.id}">${d.headline}</a></h3><div class="deal-meta">${d.sector} · ${d.countries.join(' / ')}${d.sourceName?' · '+d.sourceName:''}</div><p>${d.summary}</p><div class="card-actions"><button onclick="toggleWatch('${d.id}')">${w?'★ Watching':'☆ Watch'}</button><button onclick="toggleCompare('${d.id}')">${c?'✓ Compare':'＋ Compare'}</button></div></div><div class="deal-value">${money(d.valueBillions)}<small>reported value</small><span class="score-pill">${d.overallScore}/10</span></div></article>`}
function initHome(){if($("homeDealCount"))$("homeDealCount").textContent=deals.length;if($("featuredDeals"))$("featuredDeals").innerHTML=deals.slice(0,3).map(d=>`<a class="featured-card" href="deal.html?id=${d.id}"><span>${d.status}</span><h3>${d.headline}</h3><p>${d.summary}</p><strong>${money(d.valueBillions)}</strong></a>`).join('')}
function initDeals(){if(!$("dealList"))return;const s=$("searchInput"),sf=$("sectorFilter"),st=$("statusFilter");[...new Set(deals.map(d=>d.sector))].sort().forEach(x=>sf.insertAdjacentHTML('beforeend',`<option>${x}</option>`));function render(){const q=s.value.toLowerCase();const f=deals.filter(d=>(!q||[d.acquirer,d.target,d.headline,d.sector,...d.countries].join(' ').toLowerCase().includes(q))&&(sf.value==='all'||d.sector===sf.value)&&(st.value==='all'||d.status===st.value));$("dealList").innerHTML=f.length?f.map(dealCard).join(''):'<p class="empty-state">No matching deals.</p>';$("dealCount").textContent=f.length;$("combinedValue").textContent=money(f.reduce((a,d)=>a+d.valueBillions,0));$("crossBorderCount").textContent=f.filter(d=>d.crossBorder).length;$("averageScore").textContent=`${(f.reduce((a,d)=>a+d.scores.strategic,0)/(f.length||1)).toFixed(1)}/10`;$("resultCount").textContent=`${f.length} result${f.length===1?'':'s'}`;}[s,sf,st].forEach(x=>x.addEventListener('input',render));render()}
function score(label,n){return `<div class="score-row"><div><strong>${label}</strong><div class="score-bar"><span style="width:${n*10}%"></span></div></div><strong>${n}/10</strong></div>`}
function timeline(items){return `<div class="timeline">${items.map(x=>`<div class="timeline-item ${x.status}"><span></span><div><strong>${x.stage}</strong><small>${x.date||''}</small></div></div>`).join('')}</div>`}
function initDeal(){if(!$("dealPage"))return;const requestedId=new URLSearchParams(location.search).get('id');const d=deals.find(x=>String(x.id)===String(requestedId))||deals[0];const w=getSaved('dealScopeWatchlist').map(String).includes(String(d.id)),c=getSaved('dealScopeCompare').map(String).includes(String(d.id));$("dealPage").innerHTML=`<a class="back-link" href="deals.html">← Back to all deals</a><section class="deal-hero"><div><p class="eyebrow">${d.status} · ${d.date}</p><h1>${d.acquirer} → ${d.target}</h1><p>${d.summary}</p><div class="hero-actions"><button class="secondary-button" onclick="toggleWatch('${d.id}')">${w?'★ Remove from watchlist':'☆ Add to watchlist'}</button><button class="secondary-button" onclick="toggleCompare('${d.id}')">${c?'✓ Remove from comparison':'＋ Add to comparison'}</button></div></div><aside><span>Reported value</span><strong>${money(d.valueBillions)}</strong><small>${d.sector}<br>${d.countries.join(' / ')}</small><div class="overall-score">Overall score <b>${d.overallScore}/10</b></div></aside></section><div class="deal-layout"><article><section><h2>Summary of intent</h2><p>${d.intent}</p></section><section><h2>Long-term goals</h2><ul>${d.longTermGoals.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><h2>Cultural differences</h2><p>${d.culture}</p></section><section><h2>Geographic distance</h2><p>${d.geography}</p></section><section><h2>Financial valuation</h2><p>${d.valuation}</p></section><section><h2>Shareholder value</h2><p>${d.shareholderValue}</p></section><section><h2>Regulatory timeline</h2>${timeline(d.regulatoryTimeline)}</section><section><h2>Integration roadmap</h2>${timeline(d.integrationTimeline)}</section></article><aside class="score-panel"><h3>Deal scorecard</h3>${score('Strategic fit',d.scores.strategic)}${score('Cultural fit',d.scores.cultural)}${score('Geographic fit',d.scores.geographic)}${score('Valuation comfort',d.scores.valuation)}<a class="primary-button full" href="${d.source}" target="_blank" rel="noreferrer">Open original reporting ↗</a></aside></div>`}
function initSources(){if($("sourceGrid"))$("sourceGrid").innerHTML=outlets.map(o=>`<a class="source-card" href="${o.url}" target="_blank" rel="noreferrer"><strong>${o.name}</strong><span>${o.note}</span></a>`).join('')}
function initWatchlist(){if(!$("watchlistGrid"))return;const ids=getSaved('dealScopeWatchlist').map(String),items=deals.filter(d=>ids.includes(String(d.id)));$("watchlistGrid").innerHTML=items.length?items.map(dealCard).join(''):'<div class="empty-panel"><h2>Your watchlist is empty.</h2><p>Add deals from the Deals page or an individual deal profile.</p><a class="primary-button" href="deals.html">Browse deals</a></div>'}
function initCompare(){if(!$("compareGrid"))return;const ids=getSaved('dealScopeCompare').map(String),items=deals.filter(d=>ids.includes(String(d.id)));if(!items.length){$("compareGrid").innerHTML='<div class="empty-panel"><h2>No deals selected.</h2><p>Select up to three deals from the Deals page.</p><a class="primary-button" href="deals.html">Choose deals</a></div>';return}const rows=[['Reported value',d=>money(d.valueBillions)],['Status',d=>d.status],['Sector',d=>d.sector],['Strategic fit',d=>d.scores.strategic+'/10'],['Cultural fit',d=>d.scores.cultural+'/10'],['Geographic fit',d=>d.scores.geographic+'/10'],['Valuation comfort',d=>d.scores.valuation+'/10'],['Overall score',d=>d.overallScore+'/10']];$("compareGrid").innerHTML=`<div class="comparison-table"><div class="compare-row compare-head"><div>Metric</div>${items.map(d=>`<div><a href="deal.html?id=${d.id}">${d.acquirer} → ${d.target}</a><button onclick="toggleCompare('${d.id}')">Remove</button></div>`).join('')}</div>${rows.map(([l,fn])=>`<div class="compare-row"><strong>${l}</strong>${items.map(d=>`<div>${fn(d)}</div>`).join('')}</div>`).join('')}</div>`}
function initCompanies(){if(!$("companyGrid"))return;$("companyGrid").innerHTML=companies.map(c=>`<a class="company-card" href="company.html?id=${c.id}"><span>${c.country}</span><h3>${c.name}</h3><p>${c.description}</p><small>${c.priorDeals.length} prior deal${c.priorDeals.length===1?'':'s'} tracked</small></a>`).join('')}
function initCompany(){if(!$("companyPage"))return;const c=companies.find(x=>x.id===new URLSearchParams(location.search).get('id'))||companies[0];$("companyPage").innerHTML=`<a class="back-link" href="companies.html">← Back to companies</a><section class="page-hero"><p class="eyebrow">${c.country} · ${c.sector}</p><h1>${c.name}</h1><p>${c.description}</p></section><section class="page-section"><div class="section-heading"><div><p class="eyebrow">ACQUISITION HISTORY</p><h2>Prior transactions</h2></div></div><div class="history-list">${c.priorDeals.length?c.priorDeals.map(x=>`<article><span>${x.year}</span><div><h3>${x.name}</h3><p>${x.outcome}</p></div><strong>${x.value}</strong></article>`).join(''):'<p class="empty-state">No prior transactions are included in this sample dataset.</p>'}</div></section>`}
applyTheme();setActiveNav();initHome();initDeals();initDeal();initSources();initWatchlist();initCompare();initCompanies();initCompany();